- name: Install MySQL
  apt:
    name:
      - mysql-server
      - python3-mysqldb
    state: present

- name: Start MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Set MySQL root password
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: root
    password: "{{ mysql_root_password }}"
    host_all: yes

- name: Create database
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create MySQL user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Import sample data
  mysql_db:
    name: "{{ mysql_db }}"
    state: import
    target: roles/mysql/files/sample.sql
    login_user: root
    login_password: "{{ mysql_root_password }}"
